### ISSUE TITLE
Painterly Pack

### ISSUE THREAD

**Issue by SeveringHams** [mc-3ds-team/minecraft-3ds-unistore#12]
**What would you like to have added to the Store?**
Painterly Pack by SeveringHams, based off of Rhodox's.

**What is this content? What does it do?**
it is a texture pack, very cool

**What type of content is it? World, texture pack, skin(s), mod, misc, etc.?**
Texture Pack

**Screenshots of the content (240x400 pixel resolution is preferred)**

![2024-08-26_19-11-54 397_top](https://github.com/user-attachments/assets/6c782c88-5f28-45d5-9fec-9055c55b2f65)
![2024-08-26_19-11-32 935_top](https://github.com/user-attachments/assets/10f16040-e14a-466d-84a0-41c7cd40a47f)
![2024-08-26_19-10-23 178_top](https://github.com/user-attachments/assets/a9b1519f-ca5f-4936-92ad-6a62e485af0e)
![2024-08-26_19-08-22 274_top](https://github.com/user-attachments/assets/23d58fc1-bb11-431b-98d7-d45877ccec72)
![2024-08-26_19-06-13 429_top](https://github.com/user-attachments/assets/3af9a303-3653-4e24-b0d0-f5386a26450a)
![2024-08-26_19-05-42 320_top](https://github.com/user-attachments/assets/e7406e2e-e628-48c2-bed6-af55962fae16)
![2024-08-26_19-05-26 924_top](https://github.com/user-attachments/assets/99e389b7-af50-428c-a852-148bb3e2c511)
![2024-08-26_19-04-37 164_top](https://github.com/user-attachments/assets/91501138-626e-4741-825b-8049562d973a)

**Icon for the content (48x48 pixel resolution is preferred)**

**Repository for the content**

**Download link for the content**

[Painterly Pack by SeveringHams.zip](https://github.com/user-attachments/files/16754626/Painterly.Pack.by.SeveringHams.zip)

**Additional notes**

Original pack made by Rhodox, credit for original textures goes to him. Some textures made by SeveringHams. 
NOT COMPLETE, WORK IN PROGRESS!
Send feedback to @SeveringHams on Discord

**The developers and maintainers of this Unistore may have to modify the content for the store (such as resizing screenshots or changing the content so it may be able to be downloaded properly, etc.)**

**MAKE SURE YOU HAVE READ THE TERMS TO SUBMITTING HERE: https://github.com/Minecraft-3DS-Community/minecraft-3ds-unistore/blob/main/manual.md#requesting-content-to-be-added**

**Comment by susbaconhairman** [comment]
I will add it soon - thank you for your contribution.
