### ISSUE TITLE
Removing my content

### ISSUE THREAD

**Issue by Asriel249** [mc-3ds-team/minecraft-3ds-unistore#13]
**What would you like to have removed from the Store?**
All of my content made by me

**Why do you want it removed?**
I’ve gotten multiple requests from people to ask to remove it so

**Does it infringe any copyright? If so, how?**

Don’t think so
**Are you a part of an organization or company? If so, what is it?**
Nope

**Proof of how it is bad (copyright infringement, stolen work, etc.)**
It isn’t bad or illegal 

**Contact information:**
happy_fox249 on Discord 

**Additional notes**
srry I’ve just been asked to do this on multiple occasions 

**MAKE SURE YOU HAVE READ THE TERMS TO SUBMITTING HERE: https://github.com/Minecraft-3DS-Community/minecraft-3ds-unistore/blob/main/manual.md#requesting-content-to-be-added**

**Comment by SeveringHams** [comment]
Who was asking you?

**Comment by susbaconhairman** [comment]
I don't know who you are - could you please tell me your username that's listen in here?
Also, you should make decisions, don't let these people tell you what to do. They just want to gatekeep everything and take stuff from my store to make it obsolete - Nawrek even admitted to it.

**Comment by Asriel249** [comment]
A couple of admins from the other server

**Comment by Asriel249** [comment]
oh I’m krftrv249

**Comment by susbaconhairman** [comment]
Are you still sure you want it removed? Did they even tell you why you should take it down?

**Comment by Asriel249** [comment]
for now yes but once/if the drama cools off I’ll put it back on

**Comment by susbaconhairman** [comment]
Okay then.
