### ISSUE TITLE
TAKEDOWN REQUEST: Modernization MegaPak 1.0.0

### ISSUE THREAD

**Issue by wyndchyme** [mc-3ds-team/minecraft-3ds-unistore#14]
**What would you like to have removed from the Store?**
Modernization MegaPack

**Why do you want it removed?**
The download for this pack still functions on your UniStore, indicating that you did not comply with my previous takedown request.

**Does it infringe any copyright? If so, how?**
Contains mods that I and other modders developed for this pack – as my work is in this pack, you are infringing upon my copyright

**Are you a part of an organization or company? If so, what is it?**
Non-applicable

**Proof of how it is bad (copyright infringement, stolen work, etc.)**
Work that is hosted without permission of creators

**Contact information:**
Simply reply to this issue

**Additional notes**
God willing, do not make me request a takedown again. 

**MAKE SURE YOU HAVE READ THE TERMS TO SUBMITTING HERE: https://github.com/Minecraft-3DS-Community/minecraft-3ds-unistore/blob/main/manual.md#requesting-content-to-be-added**

**Comment by susbaconhairman** [comment]
Most of the stuff isn't even yours LMAO, also it is already removed.

**Comment by SeveringHams** [comment]
You have to redownload the unistore, because the org name changed.

**Comment by susbaconhairman** [comment]
To add on to my first comment, you did not even bother asking for permission to use people's work for your own pack. I find this ludicrous.

**Comment by wyndchyme** [comment]
> You have to redownload the unistore, because the org name changed.

The redownloaded UniStore still has a functioning download (or at least the UniStore that the QR in the readme points to.)

> To add on to my first comment, you did not even bother asking for permission to use people's work for your own pack. I find this ludicrous.

This is verifiably false.

**Comment by susbaconhairman** [comment]
> The redownloaded UniStore still has a functioning download (or at least the UniStore that the QR in the readme points to.)

No, it's completely gone from the Unistore, and it has been since you asked for me to remove it the first time.
> This is verifiably false.

Enlighten me on this then.

**Comment by SeveringHams** [comment]
Just did a text match search through the whole unistore file. The only match was some guy named MegaMiner DL 3 times in the whole file. It cannot _possibly_ still be working.

**Comment by wyndchyme** [comment]
> > The redownloaded UniStore still has a functioning download (or at least the UniStore that the QR in the readme points to.)
> 
> No, it's completely gone from the Unistore, and it has been since you asked for me to remove it the first time.

This is an error on my part and I apologize – I looked into the wrong UniStore and checking again my content is not present in your UniStore. SeveringHams is correct. 

> 
> > This is verifiably false.
> 
> Enlighten me on this then.

Cracko, Rustico, STB, Zexlo, and _you_ can all attest to me having obtained explicit permission. I literally have screenshots of you _giving me permission._ Stop spreading this blatant misinformation. 
![IMG_5790](https://github.com/user-attachments/assets/aa4d7def-0202-4aca-87a6-7b65961c52ff)

**Comment by wyndchyme** [comment]
This issue can be closed as there was no problem in the first place – unless you would care for further evidence of my recieving permission from every modder who contributed work for this pack which I am _more than willing to provide._

**Comment by susbaconhairman** [comment]
> This is an error on my part and I apologize – I looked into the wrong UniStore and checking again my content is not present in your UniStore. SeveringHams is correct.

L
> Cracko, Rustico, STB, Zexlo, and _you_ can all attest to me having obtained explicit permission. I literally have screenshots of you _giving me permission._ Stop spreading this blatant misinformation.

This is one instance. I know for a fact you did not ask Rustico.

**Comment by wyndchyme** [comment]
> > Cracko, Rustico, STB, Zexlo, and _you_ can all attest to me having obtained explicit permission. I literally have screenshots of you _giving me permission._ Stop spreading this blatant misinformation.
> 
> This is one instance. I know for a fact you did not ask Rustico.

Completely false claim on your part.

![IMG_5791](https://github.com/user-attachments/assets/85d4711d-65ac-44dd-b85d-ccbd11a45575)

**Comment by pizza-beep** [comment]
> Just did a text match search through the whole unistore file. The only matches with "mega" were 3 hits; some guy named MegaMinerDL 3 times in the whole file. It cannot _possibly_ still be working.
> 
> This is a complete fabrication. We have complied with your request, and now you're still haranguing us about it.

MegaminerDL is the goat

**Comment by susbaconhairman** [comment]
Well, you did not ask him about it first. I asked Rustico if he had given you permission to use his work AFTER you uploaded your pack, and he said no, and that he would talk to you about it.
I also had to tell you to give credit to everyone when you first uploaded it.

**Comment by wyndchyme** [comment]
> > Completely false claim on your part.
> 
> Well, you did not ask him about it first. I asked Rustico if he had given you permission to use his work AFTER you uploaded your pack, and he said no, and that he would talk to you about it. I also had to tell you to give credit to everyone when you first uploaded it.

This has been edited and I am unsure why if it is not blatant censorship.

**Comment by wyndchyme** [comment]
> Well, you did not ask him about it first. I asked Rustico if he had given you permission to use his work AFTER you uploaded your pack, and he said no, and that he would talk to you about it. I also had to tell you to give credit to everyone when you first uploaded it.

So what you're saying is that I have permission from all the modders and gave proper credit once asked. What exactly is your point here?

**Comment by SeveringHams** [comment]
You had to be told to go ask for permission, because you _first_ tried to upload it under _your_ name, with no credit to anyone at all. While it is true that you had permission _after,_ you did not have permission to _begin with/_

**Comment by susbaconhairman** [comment]
> This has been edited and I am unsure why if it is not blatant censorship.

It was an accident, sorry. No, this is not censorship.

**Comment by susbaconhairman** [comment]
> So what you're saying is that I have permission from all the modders and gave proper credit once asked. What exactly is your point here?

You lied and tried to pass everything off as your own.

**Comment by wyndchyme** [comment]
> Well, you did not ask him about it first. I asked Rustico if he had given you permission to use his work AFTER you uploaded your pack, and he said no, and that he would talk to you about it. I also had to tell you to give credit to everyone when you first uploaded it.

No, actually – the pack was still in a submission stage when permission was obtained from Rustico.

**Comment by susbaconhairman** [comment]
> No, actually – the pack was still in a submission stage when permission was obtained from Rustico.

It does not matter, you still lied.

Now, this is not the place for drama - join my server and talk about it if you'd like.

**Comment by wyndchyme** [comment]
> > So what you're saying is that I have permission from all the modders and gave proper credit once asked. What exactly is your point here?
> 
> You lied and tried to pass everything off as your own.

You are being completely disingenuous. I would literally be fine if you just stopped saying I stole this pack when I literally have permission. Credit was added prior to being uploaded to the UniStore proper while it was in the submission stage.

**Comment by SeveringHams** [comment]
> > > So what you're saying is that I have permission from all the modders and gave proper credit once asked. What exactly is your point here?
> > 
> > 
> > You lied and tried to pass everything off as your own.
> 
> You are being completely disingenuous. I would literally be fine if you just stopped saying I stole this pack when I literally have permission. Credit was added prior to being uploaded to the UniStore proper while it was in the submission stage.

Your first instinct was to just take it, put it under _your_ name, and you hadn't even bothered to ask BEFORE even using their stuff. How is he being disingenuous?

**Comment by susbaconhairman** [comment]
## **Please talk about this here: https://discord.gg/khD7nN2682**

**Comment by wyndchyme** [comment]
> > No, actually – the pack was still in a submission stage when permission was obtained from Rustico.
> 
> It does not matter, you still lied.
> 
> Now, this is not the place for drama - join my server and talk about it if you'd like.

I will not join your server. I have permission from all modders for this content and that is the end of this story. Stop spreading misinformation to further your own goals. Do not reply to this message. 

> > > > So what you're saying is that I have permission from all the modders and gave proper credit once asked. What exactly is your point here?
> > > 
> > > 
> > > You lied and tried to pass everything off as your own.
> > 
> > 
> > You are being completely disingenuous. I would literally be fine if you just stopped saying I stole this pack when I literally have permission. Credit was added prior to being uploaded to the UniStore proper while it was in the submission stage.
> 
> Your first instinct was to just take it, put it under _your_ name, and you hadn't even bothered to ask BEFORE even using their stuff. How is he being disingenuous?

This was a frankly stupid error on my part that was fixed as soon as it was called out. Many apologies were given.

**Comment by pizza-beep** [comment]
> ## **Please talk about this here: https://discord.gg/khD7nN2682**

Wasn't he banned

**Comment by wyndchyme** [comment]
I will not continue this as this has devolved into semantics. Please do not raise the issue of credit again with this pack.

**Comment by susbaconhairman** [comment]
Stop this conversation then or I will block you from this organization.

**Comment by susbaconhairman** [comment]
> Wasn't he banned

Not anymore.

**Comment by wyndchyme** [comment]
> Stop this conversation then or I will block you from this organization.

That is my plan. This conversation has been stopped, please do not reply.

**Comment by pizza-beep** [comment]
> > Wasn't he banned
> 
> Not anymore.

ALRIGHT

**Comment by SeveringHams** [comment]
> > > No, actually – the pack was still in a submission stage when permission was obtained from Rustico.
> > 
> > 
> > It does not matter, you still lied.
> > Now, this is not the place for drama - join my server and talk about it if you'd like.
> 
> I will not join your server. I have permission from all modders for this content and that is the end of this story. Stop spreading misinformation to further your own goals. Do not reply to this message.
> 
> > > > > So what you're saying is that I have permission from all the modders and gave proper credit once asked. What exactly is your point here?
> > > > 
> > > > 
> > > > You lied and tried to pass everything off as your own.
> > > 
> > > 
> > > You are being completely disingenuous. I would literally be fine if you just stopped saying I stole this pack when I literally have permission. Credit was added prior to being uploaded to the UniStore proper while it was in the submission stage.
> > 
> > 
> > Your first instinct was to just take it, put it under _your_ name, and you hadn't even bothered to ask BEFORE even using their stuff. How is he being disingenuous?
> 
> This was a frankly stupid error on my part that was fixed as soon as it was called out. Many apologies were given.

Excuse us for being at least a little bit taken aback by your extreme hostility and snarkiness the very moment you created the issue. You have been condescending and rude the whole time, and it's not unreasonable to be at least little bit annoyed and pissed when you come in and tell us we're liars and we're not complying over a user error.

**Comment by wyndchyme** [comment]
> > > > No, actually – the pack was still in a submission stage when permission was obtained from Rustico.
> > > 
> > > 
> > > It does not matter, you still lied.
> > > Now, this is not the place for drama - join my server and talk about it if you'd like.
> > 
> > 
> > I will not join your server. I have permission from all modders for this content and that is the end of this story. Stop spreading misinformation to further your own goals. Do not reply to this message.
> > > > > > So what you're saying is that I have permission from all the modders and gave proper credit once asked. What exactly is your point here?
> > > > > 
> > > > > 
> > > > > You lied and tried to pass everything off as your own.
> > > > 
> > > > 
> > > > You are being completely disingenuous. I would literally be fine if you just stopped saying I stole this pack when I literally have permission. Credit was added prior to being uploaded to the UniStore proper while it was in the submission stage.
> > > 
> > > 
> > > Your first instinct was to just take it, put it under _your_ name, and you hadn't even bothered to ask BEFORE even using their stuff. How is he being disingenuous?
> > 
> > 
> > This was a frankly stupid error on my part that was fixed as soon as it was called out. Many apologies were given.
> 
> Excuse us for being at least a little bit taken aback by your extreme hostility and snarkiness the very moment you created the issue. You have been condescending and rude the whole time, and it's not unreasonable to be at least little bit annoyed and pissed when you come in and tell us we're liars and we're not complying over a user error.

Again, my fault for raising this issue in the first place. I apologize if I seem hostile – that is due to this issue being rather heated and of course Skribbler's claims on the credit. I think we would all prefer to leave this behind now as we have nothing to gain anymore. Can we agree on this?

**Comment by SeveringHams** [comment]
Absolutely, we would be delighted to. Thank you, and have a good night!
