### ISSUE TITLE
Remove my content

### ISSUE THREAD

**Issue by DarkForPresident** [mc-3ds-team/minecraft-3ds-unistore#6]
**What would you like to have removed from the Store?**
Technoblade Skin
Technoblade's Crown
Skyblock map port
Breaking Bad skins
Sheeptastic mod port
Giant Baby Zombie mod
Broken Stronghold Chest Fix
3DSpleef
Building Time map
Randoms map demo
Frequently Asked Questions
GenSpace Mod
Mega Dropper

**Why do you want it removed?**
The owner is fully unfit and unstable and I do not want my work associated with that

**Contact information:**
vanceforpresident on discord

**Additional notes**
🙏 

**MAKE SURE YOU HAVE READ THE TERMS TO SUBMITTING HERE: https://github.com/Minecraft-3DS-Community/minecraft-3ds-unistore/blob/main/manual.md#requesting-content-to-be-added**

**Comment by susbaconhairman** [comment]
I have tried talking to you about this and it is very clear you do not want peace. I have offered very viable solutions, such as co-ownership, and you ignore that and change the subject. I will say this again - removing content from a platform like this, which is an important part of the community, leads to gatekeeping, which destroys the community. Just look at what happened to DeadSkullzJr. For the last time, PLEASE help me fix this. You have to get past your stubbornness and know that this harms all of us.

**Comment by susbaconhairman** [comment]
I have broke the Unistore - which means it doesn't work anymore. It didn't work in the first place after I made it public again actually, but this solidifies it. I am hoping this is good enough, and that it will give us some time to talk more. If none of us come to a conclusion tomorrow, then I will remove your content.

**Comment by susbaconhairman** [comment]
Everything has been removed.
